# ç½‘ç«™ faviconï¼Œæ”¯æŒsvgæˆ–å›¾ç‰‡urlï¼Œå¦‚/ig/favicon.png
# support svg or image url, such as /img/favicon.png
favicon: <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 10l7.383 7.418c.823.82.823 2.148 0 2.967a2.11 2.11 0 0 1-2.976 0L10 13"></path><path d="M6.293 15.293l-2.586-2.586a1 1 0 0 1 0-1.414l7.586-7.586a1 1 0 0 1 1.414 0l2.586 2.586a1 1 0 0 1 0 1.414l-7.586 7.586a1 1 0 0 1-1.414 0z"></path></g></svg>

# ä¸»é¢˜è‰²
# Theme color
color: hsl(238,50%,56%)

# éå¿…é¡»
# not required
# icp: è‹ICPå¤‡xxxxxxxå·

# æ˜¯å¦å¯ç”¨å·¦ä¾§æ æœç´¢input
# Is the left column search input enabled
search: true

# å·¦ä¾§æ  - è‡ªå®šä¹‰å¯¼èˆªé¡µå›¾æ ‡
# Left column - Custom navigation page icon
nav_meta:
  archives: svg
  cosy-roadmap: svg
  cosy-resume: svg
  likes: svg

# å·¦ä¾§æ  - æ–‡ç« åˆ†ç±»å›¾æ ‡ã€é¡ºåºæ§åˆ¶
# Left column - Article classification icon, order control
category_meta:
  Finance: <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g fill="none"><path d="M4 16V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v11a1 1 0 0 1-1 1H5a1 1 0 0 0 1 1h9.5a.5.5 0 0 1 0 1H6a2 2 0 0 1-2-2zM15 4a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1v11h10V4zm-8 7.25c0-.076.012-.149.031-.218c.145.11.297.21.453.3A5.109 5.109 0 0 0 10 12c.982 0 1.863-.293 2.516-.669c.156-.09.308-.19.453-.299c.02.07.031.142.031.218c0 .3-.182.55-.33.71a2.798 2.798 0 0 1-.653.505c-.52.299-1.23.535-2.017.535a4.109 4.109 0 0 1-2.017-.535a2.8 2.8 0 0 1-.654-.504C7.182 11.8 7 11.55 7 11.25zm.031-2.218A.788.788 0 0 0 7 9.25c0 .3.182.551.33.71a2.8 2.8 0 0 0 .653.505c.52.299 1.23.535 2.017.535c.788 0 1.498-.236 2.017-.535c.26-.15.485-.322.654-.504c.147-.16.329-.41.329-.71a.788.788 0 0 0-.031-.219c-.145.11-.297.21-.453.3A5.108 5.108 0 0 1 10 10a5.108 5.108 0 0 1-2.516-.669a4.273 4.273 0 0 1-.453-.299zM8 7c0-.213.126-.448.483-.655C8.841 6.137 9.374 6 10 6c.626 0 1.159.137 1.517.345c.357.207.483.442.483.655c0 .213-.126.448-.483.655C11.159 7.863 10.626 8 10 8c-.626 0-1.159-.137-1.517-.345C8.126 7.448 8 7.213 8 7zm2-2c-.755 0-1.472.163-2.019.48C7.434 5.798 7 6.313 7 7s.434 1.202.981 1.52C8.528 8.837 9.245 9 10 9c.755 0 1.472-.163 2.019-.48c.547-.318.981-.833.981-1.52s-.434-1.202-.981-1.52C11.472 5.163 10.755 5 10 5z" fill="currentColor"></path></g></svg>
  Hexo: <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M9 16h6v2H9zm4-7h-2v2H9v2h2v2h2v-2h2v-2h-2z" fill="currentColor"></path><path d="M12 2c-5.33 4.55-8 8.48-8 11.8c0 4.98 3.8 8.2 8 8.2s8-3.22 8-8.2c0-3.32-2.67-7.25-8-11.8zm0 18c-3.35 0-6-2.57-6-6.2c0-2.34 1.95-5.44 6-9.14c4.05 3.7 6 6.79 6 9.14c0 3.63-2.65 6.2-6 6.2z" fill="currentColor"></path></svg>
  Java: ğŸ˜

# æ–‡ç« å…¬å¼æ¸²æŸ“
# katex
katex:
  jsCdn: //cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.js
  cssCdn: //cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.css

# æ–‡ç« æµç¨‹å›¾ï¼Œé»˜è®¤ä¸»é¢˜ï¼šneutral
# mermaid
mermaid:
  # Available themes: default | dark | forest | neutralï¼Œdefault theme is neutral
  cdn: //cdn.jsdelivr.net/npm/mermaid@10.4.0/dist/mermaid.min.js

# æ–‡ç« è¯„è®ºï¼Œè¯·éµå®ˆç›¸å…³åœ°åŒºæ³•å¾‹æ³•è§„
# Article comments, please comply with relevant regional laws and regulations
valine:
  appId: yourValineAppId
  appKey: yourValineAppKey
  avatar: monsterid
  cdn: //unpkg.com/valine@latest/dist/Valine.min.js

# é¦–é¡µå¤©æ°”å¡ç‰‡ - å’Œé£å¤©æ°”ï¼Œå…è´¹æ³¨å†ŒAPI è¯·è®¿é—®ï¼šhttps://id.qweather.com/#/register
#Home Weather Card - Wind Weather, Free Registration API Please visit: https://id.qweather.com/#/register
weather:
  enable: true
  cityCode: 101210613
  appKey: chose-b-log-weather
